// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0a1I0ZK7-lLqtW7uZSI0cDK96wdI2Ivs',
    appId: '1:818287512219:web:71bf47e958a9b92525143e',
    messagingSenderId: '818287512219',
    projectId: 'social-224dd',
    authDomain: 'social-224dd.firebaseapp.com',
    storageBucket: 'social-224dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsyY0EnBJe5E1uKmAqHyEPGQOBvPA6n0E',
    appId: '1:818287512219:android:35514a849de8821325143e',
    messagingSenderId: '818287512219',
    projectId: 'social-224dd',
    storageBucket: 'social-224dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8a8ZFUwD8Uv86GsSAB2rSLH3BDzEPN5Q',
    appId: '1:818287512219:ios:67ea3dda4af4628025143e',
    messagingSenderId: '818287512219',
    projectId: 'social-224dd',
    storageBucket: 'social-224dd.firebasestorage.app',
    iosBundleId: 'com.example.social',
  );
}
