// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMoup_yDVDW0Ua79KtmJxIry01jlawx7s',
    appId: '1:1035769308404:web:58130d4876882b158c2aa1',
    messagingSenderId: '1035769308404',
    projectId: 'cybersecurityproject-b23f3',
    authDomain: 'cybersecurityproject-b23f3.firebaseapp.com',
    storageBucket: 'cybersecurityproject-b23f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM_SfWw7MCBOqTdxErVtyD5B2pgpeQuK8',
    appId: '1:1035769308404:android:f4fa6246fe2704248c2aa1',
    messagingSenderId: '1035769308404',
    projectId: 'cybersecurityproject-b23f3',
    storageBucket: 'cybersecurityproject-b23f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXOMjMEncspGL8Dp4QbXQZZb-fOgMcvsA',
    appId: '1:1035769308404:ios:9d23d549a15f9dc88c2aa1',
    messagingSenderId: '1035769308404',
    projectId: 'cybersecurityproject-b23f3',
    storageBucket: 'cybersecurityproject-b23f3.firebasestorage.app',
    iosBundleId: 'com.example.croWebsite',
  );
}
